a=int(input("enter a number: "))
b=int(input("enter another number: "))
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a%b)
print(a**b)
print(a//b)
print(a<b)
print(a>b)
print(a==b)
print(a!=b)
print(a<=b)
print(a>=b)
print(a and b)
print(a or b)
list1=[1,2,3,4,5]
list2=[6,7,8,9,10]

print(a in list1)
print(a not in list1)
print(a in list2)
print(a not in list2)
print(a & b)
print(a | b)
print(a ^ b)
print(a << b)
print(a >> b)
print(bin(a))
print(bin(b))